# Generated by Django 4.2.1 on 2023-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.CharField(default='08130703744', max_length=400),
            preserve_default=False,
        ),
    ]
