# Generated by Django 4.2.1 on 2023-05-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0002_rename_dob_baby_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='parent_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='parent_relationship',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baby',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
