# Generated by Django 4.2.1 on 2023-05-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        ('babies', '0003_baby_parent_name_baby_parent_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='logged_milestones',
            field=models.ManyToManyField(blank=True, to='milestones.milestone'),
        ),
    ]
