# Generated by Django 4.2.1 on 2023-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_progress'),
        ('babies', '0004_baby_logged_milestones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='logged_milestones',
            field=models.ManyToManyField(blank=True, related_name='babies', to='milestones.milestone'),
        ),
    ]
