# Generated by Django 4.2.1 on 2023-06-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_milestone_logged_by_babies'),
        ('babies', '0005_alter_baby_logged_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='milestones.progress'),
        ),
    ]
