# Generated by Django 4.2.1 on 2023-05-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0004_baby_logged_milestones'),
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('baby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='babies.baby')),
            ],
        ),
    ]
