# Generated by Django 4.2.1 on 2023-06-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0006_baby_progress'),
        ('milestones', '0003_milestone_logged_by_babies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='babies.baby'),
        ),
    ]
