# Generated by Django 4.2.1 on 2023-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_alter_progress_baby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='logged_by_babies',
        ),
        migrations.AddField(
            model_name='milestone',
            name='area',
            field=models.CharField(default='all', max_length=100),
            preserve_default=False,
        ),
    ]
