# Generated by Django 4.2.1 on 2023-06-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0006_baby_progress'),
        ('milestones', '0005_remove_milestone_logged_by_babies_milestone_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_milestones_set', to='babies.baby')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_milestones', to='milestones.milestone')),
            ],
        ),
    ]
