# Generated by Django 4.2.1 on 2023-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0007_loggedmilestone_date_observed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='imageUrls',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='nil', max_length=100),
            preserve_default=False,
        ),
    ]
